configuration:
  template_dir:
  - "git://github.com/moremoban/pypi-mobans?submodule=true&branch=dev!/templates"
  - ".moban.d"
  configuration: moban-haml.yml
targets:
  - README.rst: CUSTOM_README.rst.jj2
  - setup.py: custom_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/custom_requirements.txt.jj2"
  - "docs/source/conf.py": "docs/conf.py_t"
  - test.sh: test.script.jj2
  - "moban_haml/_version.py": "_version.py.jj2"
  - .gitignore: gitignore.jj2
  - .travis.yml: travis.yml.jj2
  - Pipfile: Pipfile.jj2
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
